
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: energy
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
